accepted = ["MIT", "Apache-2.0", "BSD-3-Clause", "Unicode-3.0", "Unlicense", "ISC", "Zlib"]
targets = [
	"x86_64-pc-windows-msvc",
	"aarch64-pc-windows-msvc",
	"x86_64-unknown-linux-musl",
	"aarch64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
