[package]
name = "refs"
version = "0.1.0"
authors = ["Matt Cavender"]
license = "MIT"
publish = false
edition = "2021"
rust-version = "1.88"

[dependencies]
clap = { version = "4", features = ["derive"] }
dunce = "1"
ignore = "0.4"
percent-encoding = "2"
tempfile = "3"

[lints.rust]
nonstandard_style = "deny"

[profile.release]
lto = true
codegen-units = 1
strip = true
