// @generated by scripts/generate-messages.mjs; do not edit by hand.
//
// Every translation of the messages GNU coreutils and git print when moving or removing a
// file, collected from the gettext catalogues (po/*.po) of these releases, fuzzy and empty
// translations skipped:
// - GNU coreutils 8.28, 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9, 9.10, 9.11, 9.12: https://ftpmirror.gnu.org/gnu/coreutils/coreutils-<version>.tar.xz
// - git 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.26.0, 2.27.0, 2.28.0, 2.29.0, 2.30.0, 2.31.0, 2.32.0, 2.33.0, 2.34.0, 2.35.0, 2.36.0, 2.37.0, 2.38.0, 2.39.0, 2.40.0, 2.41.0, 2.42.0, 2.43.0, 2.44.0, 2.45.0, 2.46.0, 2.47.0, 2.48.0, 2.49.0, 2.50.0, 2.51.0, 2.52.0, 2.53.0, 2.54.0, 2.55.0, 2.56.0: https://github.com/git/git po/ at tag v<version>
//
// A template is the literal text around each argument (`literals`, one more than the
// arguments) and the printf argument each slot prints (`arguments`, 0-based), so a
// translation that reorders `%1$s`/`%2$s` keeps its order. The English form comes first;
// each comment names the catalogues and releases holding the template.

pub struct Template {
    pub literals: &'static [&'static str],
    pub arguments: &'static [usize],
}

/// coreutils `renamed %s -> %s`: 9.5..=9.12.
/// coreutils `renamed %s -> %s` (`renamed ` translated): 8.28..=9.4.
pub const RENAMED: &[Template] = &[
    // en; 8.28..=9.12
    Template {
        literals: &["renamed ", " -> ", ""],
        arguments: &[0, 1],
    },
    // fr; 9.11..=9.12
    Template {
        literals: &["", " -> ", " renommé"],
        arguments: &[0, 1],
    },
    // de; 9.6..=9.12
    Template {
        literals: &["", " -> ", " umbenannt"],
        arguments: &[0, 1],
    },
    // ko; 9.6..=9.12
    Template {
        literals: &["", " -> ", " 이름 바꿈"],
        arguments: &[0, 1],
    },
    // fr; 9.5..=9.10
    Template {
        literals: &["", " <-> ", " renommé"],
        arguments: &[0, 1],
    },
    // de; 8.32..=9.4
    Template {
        literals: &["Datei umbenannt ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sv; 9.6..=9.12
    Template {
        literals: &["bytte namn ", " → ", ""],
        arguments: &[0, 1],
    },
    // nb; 9.2..=9.4
    Template {
        literals: &["gitt nytt navn ", " -> ", ""],
        arguments: &[0, 1],
    },
    // nb; 8.29..=9.1
    Template {
        literals: &["gitt nytt navn", " -> ", ""],
        arguments: &[0, 1],
    },
    // nl; 8.32..=9.4
    Template {
        literals: &["hernoemd ", " -> ", ""],
        arguments: &[0, 1],
    },
    // nl; 9.5..=9.12
    Template {
        literals: &["hernoemd: ", " -> ", ""],
        arguments: &[0, 1],
    },
    // hr; 8.29..=8.30
    Template {
        literals: &["imenovana datoteka ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sv; 8.28..=9.4
    Template {
        literals: &["namnändrad ", " -> ", ""],
        arguments: &[0, 1],
    },
    // et; 9.6..=9.12
    Template {
        literals: &["nimetasin ", " -> ", ""],
        arguments: &[0, 1],
    },
    // da; 8.29..=9.4
    Template {
        literals: &["omdøbte ", " -> ", ""],
        arguments: &[0, 1],
    },
    // hr; 9.6..=9.10
    Template {
        literals: &["preimenovan ", " <-> ", ""],
        arguments: &[0, 1],
    },
    // hr; 8.31..=9.4
    Template {
        literals: &["preimenovan(a/o) ", " -> ", ""],
        arguments: &[0, 1],
    },
    // hr; 9.11..=9.12
    Template {
        literals: &["preimenovano ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sl; 9.5..=9.12
    Template {
        literals: &["preimenovano: ", " -> ", ""],
        arguments: &[0, 1],
    },
    // pl; 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.6, 9.7, 9.8, 9.9, 9.10, 9.11, 9.12
    Template {
        literals: &["przemianowany ", " -> ", ""],
        arguments: &[0, 1],
    },
    // cs; 8.28..=9.4
    Template {
        literals: &["přejmenovaný ", " -> ", ""],
        arguments: &[0, 1],
    },
    // cs; 9.6..=9.12
    Template {
        literals: &["přejmenováno ", " → ", ""],
        arguments: &[0, 1],
    },
    // pt, pt_BR; 8.28, 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.7, 9.8, 9.9, 9.10, 9.11, 9.12
    Template {
        literals: &["renomeado ", " -> ", ""],
        arguments: &[0, 1],
    },
    // pt; 8.31
    Template {
        literals: &["renomeado para", " -> ", ""],
        arguments: &[0, 1],
    },
    // fr; 8.32..=9.4
    Template {
        literals: &["renommé ", " -> ", ""],
        arguments: &[0, 1],
    },
    // fr; 8.29..=8.31
    Template {
        literals: &["renommé", " -> ", ""],
        arguments: &[0, 1],
    },
    // ro; 9.2..=9.4
    Template {
        literals: &["s-a redenumit ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ro; 9.5..=9.12
    Template {
        literals: &["s-a redenumit ", " <-> ", ""],
        arguments: &[0, 1],
    },
    // ca; 8.30..=9.4
    Template {
        literals: &["s’ha reanomenat ", " -> ", ""],
        arguments: &[0, 1],
    },
    // fi; 8.32..=9.4
    Template {
        literals: &["uudelleennimetty ", " -> ", ""],
        arguments: &[0, 1],
    },
    // tr; 9.1..=9.4
    Template {
        literals: &["yeniden adlandırıldı: ", " -> ", ""],
        arguments: &[0, 1],
    },
    // hu; 8.30..=9.4
    Template {
        literals: &["átnevezve", " -> ", ""],
        arguments: &[0, 1],
    },
    // et; 8.28..=9.4
    Template {
        literals: &["ümbernimetatud ", " -> ", ""],
        arguments: &[0, 1],
    },
    // vi; 8.28..=9.4
    Template {
        literals: &["đã đổi tên", " -> ", ""],
        arguments: &[0, 1],
    },
    // ru; 8.29..=9.4
    Template {
        literals: &["переименован ", " -> ", ""],
        arguments: &[0, 1],
    },
    // uk; 8.30..=9.12
    Template {
        literals: &["перейменовано ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sr; 9.0..=9.4
    Template {
        literals: &["преименовано ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sr; 9.6..=9.12
    Template {
        literals: &["преименовах „", "“ → „", "“"],
        arguments: &[0, 1],
    },
    // bg; 9.7..=9.12
    Template {
        literals: &["преименуван „", "“ на „", "“"],
        arguments: &[0, 1],
    },
    // bg; 8.31..=9.4
    Template {
        literals: &["преименуван", " -> ", ""],
        arguments: &[0, 1],
    },
    // ar; 9.10..=9.12
    Template {
        literals: &["غُيّر الاسم ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ka; 9.2..=9.4
    Template {
        literals: &["გადარქმეულია ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ka; 9.8..=9.12
    Template {
        literals: &["სახელცვლილია ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ja; 9.0, 9.1, 9.2, 9.3, 9.4, 9.8, 9.9, 9.10, 9.11, 9.12
    Template {
        literals: &["名前変更: ", " -> ", ""],
        arguments: &[0, 1],
    },
    // zh_CN; 8.31..=9.12
    Template {
        literals: &["已重命名 ", " -> ", ""],
        arguments: &[0, 1],
    },
    // zh_TW; 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.12
    Template {
        literals: &["已重新命名 ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ko; 9.0..=9.4
    Template {
        literals: &["이름 바꿈 ", " -> ", ""],
        arguments: &[0, 1],
    },
];

/// coreutils `copied %s -> %s`: 9.5..=9.12.
/// coreutils `copied %s -> %s` (`copied ` translated): 8.28..=9.4.
pub const COPIED: &[Template] = &[
    // en; 8.28..=9.12
    Template {
        literals: &["copied ", " -> ", ""],
        arguments: &[0, 1],
    },
    // de; 9.6..=9.12
    Template {
        literals: &["", " -> ", " kopiert"],
        arguments: &[0, 1],
    },
    // ko; 9.5..=9.12
    Template {
        literals: &["", " -> ", " 복사함"],
        arguments: &[0, 1],
    },
    // de; 8.32..=9.4
    Template {
        literals: &["Datei kopiert ", " -> ", ""],
        arguments: &[0, 1],
    },
    // pt; 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.7, 9.8, 9.9, 9.10, 9.11, 9.12
    Template {
        literals: &["copiada ", " -> ", ""],
        arguments: &[0, 1],
    },
    // pt_BR; 8.28, 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.12
    Template {
        literals: &["copiado ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ro; 9.2..=9.4
    Template {
        literals: &["copiat ", " -> ", ""],
        arguments: &[0, 1],
    },
    // fr; 8.31..=9.12
    Template {
        literals: &["copié ", " -> ", ""],
        arguments: &[0, 1],
    },
    // fr; 8.29..=8.30
    Template {
        literals: &["copié", " -> ", ""],
        arguments: &[0, 1],
    },
    // nl; 8.32..=9.4
    Template {
        literals: &["gekopieerd ", " -> ", ""],
        arguments: &[0, 1],
    },
    // nl; 9.5..=9.12
    Template {
        literals: &["gekopieerd: ", " -> ", ""],
        arguments: &[0, 1],
    },
    // et; 8.28, 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.6, 9.7, 9.8, 9.9, 9.10, 9.11, 9.12
    Template {
        literals: &["kopeeritud ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sv; 8.28..=9.4
    Template {
        literals: &["kopierade ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sv; 9.6..=9.12
    Template {
        literals: &["kopierade ", " → ", ""],
        arguments: &[0, 1],
    },
    // da; 8.29..=9.4
    Template {
        literals: &["kopierede ", " -> ", ""],
        arguments: &[0, 1],
    },
    // nb; 9.2..=9.4
    Template {
        literals: &["kopiert ", " -> ", ""],
        arguments: &[0, 1],
    },
    // nb; 8.29..=9.1
    Template {
        literals: &["kopiert", " -> ", ""],
        arguments: &[0, 1],
    },
    // fi; 9.0..=9.4
    Template {
        literals: &["kopioitu ", " -> ", ""],
        arguments: &[0, 1],
    },
    // pl; 9.12
    Template {
        literals: &["kopiowany ", " -> ", ""],
        arguments: &[0, 1],
    },
    // hr; 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.6, 9.7, 9.8, 9.9, 9.10, 9.11, 9.12
    Template {
        literals: &["kopirano ", " -> ", ""],
        arguments: &[0, 1],
    },
    // tr; 9.1..=9.4
    Template {
        literals: &["kopyalandı: ", " -> ", ""],
        arguments: &[0, 1],
    },
    // hu; 8.30..=9.4
    Template {
        literals: &["másolva", " -> ", ""],
        arguments: &[0, 1],
    },
    // sl; 9.6..=9.12
    Template {
        literals: &["prepisano ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ro; 9.5..=9.12
    Template {
        literals: &["s-a copiat ", " -> ", ""],
        arguments: &[0, 1],
    },
    // pl; 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.6, 9.7, 9.8, 9.9, 9.10, 9.11
    Template {
        literals: &["skopiowany ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ca; 8.30..=9.4
    Template {
        literals: &["s’ha copiat ", " -> ", ""],
        arguments: &[0, 1],
    },
    // cs; 8.28..=9.4
    Template {
        literals: &["zkopírovaný", " -> ", ""],
        arguments: &[0, 1],
    },
    // cs; 9.6..=9.12
    Template {
        literals: &["zkopírováno ", " → ", ""],
        arguments: &[0, 1],
    },
    // vi; 8.28..=9.4
    Template {
        literals: &["đã chép", " -> ", ""],
        arguments: &[0, 1],
    },
    // bg; 8.31..=9.4
    Template {
        literals: &["копиран ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ru; 8.29..=9.4
    Template {
        literals: &["скопирован ", " -> ", ""],
        arguments: &[0, 1],
    },
    // uk; 8.30..=9.12
    Template {
        literals: &["скопійовано ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sr; 9.0..=9.4
    Template {
        literals: &["умножено ", " -> ", ""],
        arguments: &[0, 1],
    },
    // sr; 9.6..=9.12
    Template {
        literals: &["умножих „", "“ → „", "“"],
        arguments: &[0, 1],
    },
    // ar; 9.10..=9.12
    Template {
        literals: &["نُسخ ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ka; 9.8..=9.12
    Template {
        literals: &["დაკოპირდა ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ka; 9.2..=9.4
    Template {
        literals: &["კოპირებულია ", " -> ", ""],
        arguments: &[0, 1],
    },
    // bg; 9.7..=9.12
    Template {
        literals: &["„", "“ копиран в „", "“"],
        arguments: &[0, 1],
    },
    // ja; 9.0, 9.1, 9.2, 9.3, 9.4, 9.8, 9.9, 9.10, 9.11, 9.12
    Template {
        literals: &["コピー: ", " -> ", ""],
        arguments: &[0, 1],
    },
    // zh_CN; 8.31..=9.12
    Template {
        literals: &["已复制 ", " -> ", ""],
        arguments: &[0, 1],
    },
    // zh_TW; 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.12
    Template {
        literals: &["已複製 ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ko; 9.1..=9.4
    Template {
        literals: &["복사함 ", " -> ", ""],
        arguments: &[0, 1],
    },
    // ko; 9.0
    Template {
        literals: &["복사함", " -> ", ""],
        arguments: &[0, 1],
    },
];

/// coreutils `removed %s\n`: 8.28..=9.12.
pub const REMOVED: &[Template] = &[
    // en; 8.28..=9.12
    Template {
        literals: &["removed ", ""],
        arguments: &[0],
    },
    // es; 8.28..=9.12
    Template {
        literals: &["", " borrado"],
        arguments: &[0],
    },
    // ms; 8.28..=9.12
    Template {
        literals: &["", " dibuang"],
        arguments: &[0],
    },
    // et; 8.28..=9.12
    Template {
        literals: &["", " eemaldatud"],
        arguments: &[0],
    },
    // lg; 8.28..=9.12
    Template {
        literals: &["", " egyidwawo"],
        arguments: &[0],
    },
    // nb; 8.28..=9.12
    Template {
        literals: &["", " er fjernet"],
        arguments: &[0],
    },
    // eu; 8.28..=9.12
    Template {
        literals: &["", " ezabatua"],
        arguments: &[0],
    },
    // nl; 8.28..=9.12
    Template {
        literals: &["", " is verwijderd"],
        arguments: &[0],
    },
    // af; 8.28..=9.12
    Template {
        literals: &["", " is verwyder."],
        arguments: &[0],
    },
    // hr; 8.28..=8.29
    Template {
        literals: &["", " je uklonjen"],
        arguments: &[0],
    },
    // pt; 8.28..=9.12
    Template {
        literals: &["", " removido"],
        arguments: &[0],
    },
    // it; 8.28..=9.12
    Template {
        literals: &["", " rimosso"],
        arguments: &[0],
    },
    // ga; 8.28..=9.12
    Template {
        literals: &["", " scriosta"],
        arguments: &[0],
    },
    // tr; 8.28..=9.12
    Template {
        literals: &["", " silindi"],
        arguments: &[0],
    },
    // fr; 8.28..=9.12
    Template {
        literals: &["", " supprimé"],
        arguments: &[0],
    },
    // hu; 8.28..=9.12
    Template {
        literals: &["", " törölve"],
        arguments: &[0],
    },
    // de; 8.28..=9.12
    Template {
        literals: &["", " wurde entfernt"],
        arguments: &[0],
    },
    // bg; 8.28..=8.30
    Template {
        literals: &["", " е изтрит"],
        arguments: &[0],
    },
    // ta; 9.4..=9.12
    Template {
        literals: &["", " நீக்கப்பட்டது"],
        arguments: &[0],
    },
    // ja; 8.28..=9.12
    Template {
        literals: &["", " を削除しました"],
        arguments: &[0],
    },
    // ko; 9.0..=9.12
    Template {
        literals: &["", "을(를) 제거했습니다"],
        arguments: &[0],
    },
    // ro; 8.28..=9.1
    Template {
        literals: &["eliminat ", ""],
        arguments: &[0],
    },
    // da; 8.28..=9.12
    Template {
        literals: &["fjernede ", ""],
        arguments: &[0],
    },
    // eo; 8.28..=9.12
    Template {
        literals: &["forigiĝis ", ""],
        arguments: &[0],
    },
    // id; 8.28..=9.12
    Template {
        literals: &["menghapus ", ""],
        arguments: &[0],
    },
    // sl; 8.28..=9.12
    Template {
        literals: &["odstranjena ", ""],
        arguments: &[0],
    },
    // sk; 8.28..=9.12
    Template {
        literals: &["odstránené ", ""],
        arguments: &[0],
    },
    // lt; 8.28..=9.12
    Template {
        literals: &["pašalintas ", ""],
        arguments: &[0],
    },
    // fi; 8.28..=9.12
    Template {
        literals: &["poistettiin tiedosto ", ""],
        arguments: &[0],
    },
    // pt_BR; 8.28..=9.12
    Template {
        literals: &["removido ", ""],
        arguments: &[0],
    },
    // ro; 9.2..=9.12
    Template {
        literals: &["s-a eliminat ", ""],
        arguments: &[0],
    },
    // cs; 8.28..=9.12
    Template {
        literals: &["smazáno ", ""],
        arguments: &[0],
    },
    // ca; 8.28..=9.12
    Template {
        literals: &["s’ha eliminat ", ""],
        arguments: &[0],
    },
    // sv; 8.28..=9.12
    Template {
        literals: &["tog bort ", ""],
        arguments: &[0],
    },
    // hr; 9.6..=9.12
    Template {
        literals: &["uklonjen je ", ""],
        arguments: &[0],
    },
    // hr; 8.30..=9.5
    Template {
        literals: &["uklonjeni je ", ""],
        arguments: &[0],
    },
    // pl; 8.28..=9.12
    Template {
        literals: &["usunięty ", ""],
        arguments: &[0],
    },
    // vi; 8.28..=9.12
    Template {
        literals: &["đã xóa ", ""],
        arguments: &[0],
    },
    // uk; 8.28..=9.12
    Template {
        literals: &["вилучено ", ""],
        arguments: &[0],
    },
    // be; 8.28..=9.12
    Template {
        literals: &["выдален ", ""],
        arguments: &[0],
    },
    // ru; 8.28..=9.12
    Template {
        literals: &["удалён ", ""],
        arguments: &[0],
    },
    // sr; 8.28..=9.12
    Template {
        literals: &["уклонио сам „", "“"],
        arguments: &[0],
    },
    // ar; 9.10..=9.12
    Template {
        literals: &["حُذِف ", ""],
        arguments: &[0],
    },
    // ka; 9.2..=9.12
    Template {
        literals: &["წაშლილია ", "."],
        arguments: &[0],
    },
    // bg; 8.31..=9.12
    Template {
        literals: &["„", "“ е изтрит"],
        arguments: &[0],
    },
    // zh_CN; 8.31..=9.12
    Template {
        literals: &["已删除 ", ""],
        arguments: &[0],
    },
    // zh_CN; 8.28..=8.30
    Template {
        literals: &["已删除", ""],
        arguments: &[0],
    },
    // zh_TW; 8.32..=9.12
    Template {
        literals: &["已刪除 ", ""],
        arguments: &[0],
    },
    // zh_TW; 8.28..=8.31
    Template {
        literals: &["已移除", ""],
        arguments: &[0],
    },
];

/// coreutils `removed directory %s\n`: 8.28..=9.12.
pub const REMOVED_DIRECTORY: &[Template] = &[
    // en; 8.28..=9.12
    Template {
        literals: &["removed directory ", ""],
        arguments: &[0],
    },
    // tr; 9.1..=9.12
    Template {
        literals: &["", " dizini kaldırıldı"],
        arguments: &[0],
    },
    // hu; 8.28..=9.12
    Template {
        literals: &["", " könyvtár törölve"],
        arguments: &[0],
    },
    // ko; 9.0..=9.12
    Template {
        literals: &["", " 디렉터리를 제거했습니다"],
        arguments: &[0],
    },
    // de; 8.28..=9.12
    Template {
        literals: &["Verzeichnis ", " wurde entfernt"],
        arguments: &[0],
    },
    // cs; 8.28..=9.12
    Template {
        literals: &["adresář ", " smazán"],
        arguments: &[0],
    },
    // da; 8.28..=9.12
    Template {
        literals: &["fjernede kataloget ", ""],
        arguments: &[0],
    },
    // pt_BR; 8.28..=9.12
    Template {
        literals: &["foi removido o diretório: ", ""],
        arguments: &[0],
    },
    // et; 8.28..=9.12
    Template {
        literals: &["kustutatud kataloog ", ""],
        arguments: &[0],
    },
    // nl; 8.28..=9.12
    Template {
        literals: &["map ", " is verwijderd"],
        arguments: &[0],
    },
    // nb; 8.28..=9.12
    Template {
        literals: &["mappa ", " er fjernet"],
        arguments: &[0],
    },
    // sl; 8.28..=9.12
    Template {
        literals: &["odstranjen imenik ", ""],
        arguments: &[0],
    },
    // pt; 8.31..=9.12
    Template {
        literals: &["pasta removida: ", ""],
        arguments: &[0],
    },
    // fi; 8.28..=9.12
    Template {
        literals: &["poistettiin hakemisto ", ""],
        arguments: &[0],
    },
    // fr; 8.28..=9.12
    Template {
        literals: &["répertoire ", " supprimé"],
        arguments: &[0],
    },
    // ro; 9.2..=9.12
    Template {
        literals: &["s-a eliminat directorul ", ""],
        arguments: &[0],
    },
    // ca; 8.30..=9.12
    Template {
        literals: &["s’ha eliminat el directori ", ""],
        arguments: &[0],
    },
    // sv; 8.28..=9.12
    Template {
        literals: &["tog bort katalogen ", ""],
        arguments: &[0],
    },
    // hr; 8.28, 8.29, 9.11, 9.12
    Template {
        literals: &["uklonjen direktorij ", ""],
        arguments: &[0],
    },
    // hr; 8.30..=9.10
    Template {
        literals: &["uklonjeni direktorij ", ""],
        arguments: &[0],
    },
    // pl; 8.28..=9.12
    Template {
        literals: &["usunięty katalog ", ""],
        arguments: &[0],
    },
    // vi; 8.28..=9.12
    Template {
        literals: &["đã xóa thư mục ", ""],
        arguments: &[0],
    },
    // uk; 8.28..=9.12
    Template {
        literals: &["вилучено каталог ", ""],
        arguments: &[0],
    },
    // bg; 8.32..=9.12
    Template {
        literals: &["директорията „", "“ бе изтрита"],
        arguments: &[0],
    },
    // ru; 8.28..=8.30
    Template {
        literals: &["удален каталог ", ""],
        arguments: &[0],
    },
    // ru; 8.31..=9.12
    Template {
        literals: &["удалён каталог ", ""],
        arguments: &[0],
    },
    // sr; 8.28..=9.12
    Template {
        literals: &["уклоњени директоријум „", "“"],
        arguments: &[0],
    },
    // ar; 9.10..=9.12
    Template {
        literals: &["حُذف الدليل ", ""],
        arguments: &[0],
    },
    // ka; 9.2..=9.12
    Template {
        literals: &["საქაღალდე წაიშალა ", ""],
        arguments: &[0],
    },
    // ja; 9.0..=9.12
    Template {
        literals: &["ディレクトリ ", " を削除しました"],
        arguments: &[0],
    },
    // zh_CN; 8.31..=9.12
    Template {
        literals: &["已删除目录 ", ""],
        arguments: &[0],
    },
    // zh_TW; 8.32..=9.12
    Template {
        literals: &["已刪除目錄 ", ""],
        arguments: &[0],
    },
];

/// coreutils `created directory %s`: 8.28..=9.12.
/// coreutils `created directory %s\n`: 8.28..=9.12.
pub const CREATED_DIRECTORY: &[Template] = &[
    // en; 8.28..=9.12
    Template {
        literals: &["created directory ", ""],
        arguments: &[0],
    },
    // eu; 8.28..=9.12
    Template {
        literals: &["", " direktorioa sortua"],
        arguments: &[0],
    },
    // tr; 9.1..=9.12
    Template {
        literals: &["", " dizini oluşturuldu"],
        arguments: &[0],
    },
    // hu; 8.28..=9.12
    Template {
        literals: &["", " könyvtár létrejött"],
        arguments: &[0],
    },
    // ko; 9.0..=9.12
    Template {
        literals: &["", " 디렉터리를 만들 수 없습니다"],
        arguments: &[0],
    },
    // ko; 9.0..=9.12
    Template {
        literals: &["", " 디렉터리를 만들었습니다"],
        arguments: &[0],
    },
    // de; 8.28..=9.12
    Template {
        literals: &["Verzeichnis ", " angelegt"],
        arguments: &[0],
    },
    // cs; 8.28..=9.12
    Template {
        literals: &["adresář ", " vytvořen"],
        arguments: &[0],
    },
    // sk; 8.28..=9.12
    Template {
        literals: &["bol vytvorený adresár ", ""],
        arguments: &[0],
    },
    // ro; 8.28..=9.1
    Template {
        literals: &["creat dosarul ", ""],
        arguments: &[0],
    },
    // pt_BR; 8.28..=9.12
    Template {
        literals: &["criado o diretório ", ""],
        arguments: &[0],
    },
    // ga; 8.28..=9.12
    Template {
        literals: &["cruthaíodh comhadlann ", ""],
        arguments: &[0],
    },
    // fr; 8.28..=9.12
    Template {
        literals: &["création du répertoire ", ""],
        arguments: &[0],
    },
    // it; 8.28..=9.12
    Template {
        literals: &["directory ", " creata"],
        arguments: &[0],
    },
    // id; 8.28..=9.12
    Template {
        literals: &["direktori ", " dibuat"],
        arguments: &[0],
    },
    // ms; 8.28..=9.12
    Template {
        literals: &["direktori ", " dicipta"],
        arguments: &[0],
    },
    // tr; 8.28..=9.0
    Template {
        literals: &["dizin ", " oluşturuldu"],
        arguments: &[0],
    },
    // pt_BR; 8.28..=9.12
    Template {
        literals: &["foi criado o diretório ", ""],
        arguments: &[0],
    },
    // af; 8.28..=9.12
    Template {
        literals: &["gids ", " is geskep"],
        arguments: &[0],
    },
    // et; 8.28..=9.12
    Template {
        literals: &["kataloog ", " on loodud"],
        arguments: &[0],
    },
    // hr; 8.28..=9.10
    Template {
        literals: &["kreiran je direktorij ", ""],
        arguments: &[0],
    },
    // eo; 8.28..=9.12
    Template {
        literals: &["kreiĝas dosierujo ", ""],
        arguments: &[0],
    },
    // fi; 8.28..=9.12
    Template {
        literals: &["luotiin hakemisto ", ""],
        arguments: &[0],
    },
    // nl; 8.28..=9.12
    Template {
        literals: &["map ", " is aangemaakt"],
        arguments: &[0],
    },
    // nb; 8.28..=9.12
    Template {
        literals: &["mappa ", " er opprettet"],
        arguments: &[0],
    },
    // lg; 8.28..=9.12
    Template {
        literals: &["nkozewo tterekero eliyitibwa ", ""],
        arguments: &[0],
    },
    // da; 8.28..=9.12
    Template {
        literals: &["oprettede katalog ", ""],
        arguments: &[0],
    },
    // da; 8.29..=9.12
    Template {
        literals: &["oprettede kataloget ", ""],
        arguments: &[0],
    },
    // pt; 8.28..=9.12
    Template {
        literals: &["pasta ", " criada"],
        arguments: &[0],
    },
    // fr; 8.29..=9.12
    Template {
        literals: &["répertoire ", " créé"],
        arguments: &[0],
    },
    // ro; 9.2..=9.12
    Template {
        literals: &["s-a creat directorul ", ""],
        arguments: &[0],
    },
    // es; 8.28..=9.12
    Template {
        literals: &["se ha creado el directorio ", ""],
        arguments: &[0],
    },
    // sv; 8.28..=9.12
    Template {
        literals: &["skapade katalog ", ""],
        arguments: &[0],
    },
    // sv; 8.28..=9.12
    Template {
        literals: &["skapade katalogen ", ""],
        arguments: &[0],
    },
    // hr; 8.30, 9.11, 9.12
    Template {
        literals: &["stvoren je direktorij ", ""],
        arguments: &[0],
    },
    // lt; 8.28..=9.12
    Template {
        literals: &["sukurtas aplankas ", ""],
        arguments: &[0],
    },
    // ca; 8.28..=9.12
    Template {
        literals: &["s’ha creat el directori ", ""],
        arguments: &[0],
    },
    // sl; 8.28..=9.12
    Template {
        literals: &["ustvarjen imenik ", ""],
        arguments: &[0],
    },
    // pl; 8.28..=9.12
    Template {
        literals: &["utworzony katalog ", ""],
        arguments: &[0],
    },
    // vi; 8.28..=9.12
    Template {
        literals: &["đã tạo thư mục ", ""],
        arguments: &[0],
    },
    // sr; 8.28..=9.12
    Template {
        literals: &["направих директоријум „", "“"],
        arguments: &[0],
    },
    // ru; 8.28..=9.12
    Template {
        literals: &["создан каталог ", ""],
        arguments: &[0],
    },
    // be; 8.28..=9.12
    Template {
        literals: &["створана тэчка ", ""],
        arguments: &[0],
    },
    // uk; 8.28..=9.12
    Template {
        literals: &["створений каталог ", ""],
        arguments: &[0],
    },
    // uk; 8.30..=9.12
    Template {
        literals: &["створено каталог ", ""],
        arguments: &[0],
    },
    // bg; 8.28..=8.31
    Template {
        literals: &["създаден е каталог ", ""],
        arguments: &[0],
    },
    // bg; 8.31..=9.12
    Template {
        literals: &["създадена е директория „", "“"],
        arguments: &[0],
    },
    // ar; 9.10..=9.12
    Template {
        literals: &["أُنشئ الدليل ", ""],
        arguments: &[0],
    },
    // ar; 9.10..=9.12
    Template {
        literals: &["دليل منشأ ", ""],
        arguments: &[0],
    },
    // ka; 9.2..=9.12
    Template {
        literals: &["შეიქმნა საქაღალდე: ", ""],
        arguments: &[0],
    },
    // ja; 8.28..=9.12
    Template {
        literals: &["ディレクトリ ", " を作成しました"],
        arguments: &[0],
    },
    // zh_CN; 8.28..=9.12
    Template {
        literals: &["已创建目录 ", ""],
        arguments: &[0],
    },
    // zh_TW; 8.32..=9.12
    Template {
        literals: &["已建立目錄 ", ""],
        arguments: &[0],
    },
];

/// coreutils ` (backup: %s)`: 8.28..=9.12.
pub const BACKUP: &[Template] = &[
    // en, id, it, ms; 8.28..=9.12
    Template {
        literals: &[" (backup: ", ")"],
        arguments: &[0],
    },
    // de; 8.28..=9.12
    Template {
        literals: &[" (Sicherung: ", ")"],
        arguments: &[0],
    },
    // fr; 8.28..=9.12
    Template {
        literals: &[" (archive : ", ")"],
        arguments: &[0],
    },
    // lt; 8.28..=9.12
    Template {
        literals: &[" (atsarginė kopija: ", ")"],
        arguments: &[0],
    },
    // eu; 8.28..=9.12
    Template {
        literals: &[" (babeskopia: ", ")"],
        arguments: &[0],
    },
    // hu; 8.28..=9.12
    Template {
        literals: &[" (biztonsági mentés: ", ")"],
        arguments: &[0],
    },
    // gl; 8.28..=9.12
    Template {
        literals: &[" (copia de seguridade: ", ")"],
        arguments: &[0],
    },
    // ro; 9.2..=9.12
    Template {
        literals: &[" (copie de rezervă: ", ")"],
        arguments: &[0],
    },
    // ca; 8.28..=9.12
    Template {
        literals: &[" (còpia de seguretat: ", ")"],
        arguments: &[0],
    },
    // pt_BR; 8.28..=9.12
    Template {
        literals: &[" (cópia de segurança: ", ")"],
        arguments: &[0],
    },
    // ga; 8.28..=9.12
    Template {
        literals: &[" (cúltaca: ", ")"],
        arguments: &[0],
    },
    // lg; 8.28..=9.12
    Template {
        literals: &[" (kkopi ey'okwerinda: ", ")"],
        arguments: &[0],
    },
    // pl; 8.28..=9.12
    Template {
        literals: &[" (kopia zapasowa: ", ")"],
        arguments: &[0],
    },
    // hr; 9.6..=9.10
    Template {
        literals: &[" (osiguranje, sigurnosna kopija: ", ")"],
        arguments: &[0],
    },
    // nl; 8.28..=9.12
    Template {
        literals: &[" (reservekopie: ", ")"],
        arguments: &[0],
    },
    // es; 8.28..=9.12
    Template {
        literals: &[" (respaldo: ", ")"],
        arguments: &[0],
    },
    // ro; 8.28..=9.1
    Template {
        literals: &[" (rezervă: ", ")"],
        arguments: &[0],
    },
    // pt; 8.28..=8.30
    Template {
        literals: &[" (salvaguarda: ", ")"],
        arguments: &[0],
    },
    // vi; 8.28..=9.12
    Template {
        literals: &[" (sao lưu: ", ")"],
        arguments: &[0],
    },
    // eo; 8.28..=9.12
    Template {
        literals: &[" (savkopio: ", ")"],
        arguments: &[0],
    },
    // pt; 8.31..=9.12
    Template {
        literals: &[" (segurança: ", ")"],
        arguments: &[0],
    },
    // hr; 8.28, 8.29, 8.30, 8.31, 8.32, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.11, 9.12
    Template {
        literals: &[" (sigurnosna kopija: ", ")"],
        arguments: &[0],
    },
    // da; 8.28..=9.12
    Template {
        literals: &[" (sikkerhedskopi: ", ")"],
        arguments: &[0],
    },
    // nb; 8.28..=9.12
    Template {
        literals: &[" (sikkerhetskopi: ", ")"],
        arguments: &[0],
    },
    // sv; 8.28..=9.12
    Template {
        literals: &[" (säkerhetskopia: ", ")"],
        arguments: &[0],
    },
    // fi; 8.28..=9.12
    Template {
        literals: &[" (varmuuskopio: ", ")"],
        arguments: &[0],
    },
    // sl; 8.28..=9.12
    Template {
        literals: &[" (varnostna kopija: ", ")"],
        arguments: &[0],
    },
    // et; 8.28..=9.12
    Template {
        literals: &[" (varukoopia: ", ")"],
        arguments: &[0],
    },
    // tr; 8.28..=9.12
    Template {
        literals: &[" (yedek: ", ")"],
        arguments: &[0],
    },
    // cs; 8.28..=9.12
    Template {
        literals: &[" (záloha: ", ")"],
        arguments: &[0],
    },
    // el; 8.28..=9.12
    Template {
        literals: &[" (αντίγραφο ασφαλείας: ", ")"],
        arguments: &[0],
    },
    // be; 8.28..=9.12
    Template {
        literals: &[" (запасны: ", ")"],
        arguments: &[0],
    },
    // sr; 8.28..=9.12
    Template {
        literals: &[" (резерва: ", ")"],
        arguments: &[0],
    },
    // uk; 8.28..=9.12
    Template {
        literals: &[" (резервна копія: ", ")"],
        arguments: &[0],
    },
    // ru; 8.28..=9.12
    Template {
        literals: &[" (резервная копия: ", ")"],
        arguments: &[0],
    },
    // bg; 8.28..=8.30
    Template {
        literals: &[" (резервно копие: ", ")"],
        arguments: &[0],
    },
    // bg; 8.31..=9.12
    Template {
        literals: &[" (резервно копие: „", "“)"],
        arguments: &[0],
    },
    // ar; 9.10..=9.12
    Template {
        literals: &[" (نسخة احتياطية: ", ")"],
        arguments: &[0],
    },
    // ta; 9.4..=9.12
    Template {
        literals: &[" (காப்புப்படி: ", ")"],
        arguments: &[0],
    },
    // ka; 9.2..=9.12
    Template {
        literals: &[" (მარქაფი: ", ")"],
        arguments: &[0],
    },
    // ja; 8.28..=9.12
    Template {
        literals: &[" (バックアップ: ", ")"],
        arguments: &[0],
    },
    // zh_TW; 8.28..=9.12
    Template {
        literals: &[" (備份：", ")"],
        arguments: &[0],
    },
    // zh_CN; 8.28..=9.0
    Template {
        literals: &[" (备份：", ")"],
        arguments: &[0],
    },
    // ko; 8.28..=9.12
    Template {
        literals: &[" (백업: ", ")"],
        arguments: &[0],
    },
    // af; 8.28..=9.12
    Template {
        literals: &["(rugsteun: ", ")"],
        arguments: &[0],
    },
    // sk; 8.28..=9.12
    Template {
        literals: &["(záloha: ", ")"],
        arguments: &[0],
    },
    // zh_CN; 9.1..=9.12
    Template {
        literals: &["（备份：", "）"],
        arguments: &[0],
    },
];

/// git `Renaming %s to %s\n`: 2.20.0..=2.56.0.
pub const RENAMING: &[Template] = &[
    // en; 2.20.0..=2.56.0
    Template {
        literals: &["Renaming ", " to ", ""],
        arguments: &[0, 1],
    },
    // tr; 2.26.0..=2.56.0
    Template {
        literals: &["", ", ", " olarak yeniden adlandırılıyor"],
        arguments: &[0, 1],
    },
    // pt_PT; 2.20.0..=2.56.0
    Template {
        literals: &["A mudar de nome de ", " para ", ""],
        arguments: &[0, 1],
    },
    // ga; 2.50.0..=2.56.0
    Template {
        literals: &["Athainmniú ", " go ", ""],
        arguments: &[0, 1],
    },
    // de; 2.20.0..=2.56.0
    Template {
        literals: &["Benenne ", " nach ", " um"],
        arguments: &[0, 1],
    },
    // sv; 2.20.0..=2.56.0
    Template {
        literals: &["Byter namn på ", " till ", ""],
        arguments: &[0, 1],
    },
    // ca; 2.56.0
    Template {
        literals: &["Es canvia el nom de ", " a ", ""],
        arguments: &[0, 1],
    },
    // af; 2.56.0
    Template {
        literals: &["Hernoem ", " na ", ""],
        arguments: &[0, 1],
    },
    // id; 2.32.0..=2.56.0
    Template {
        literals: &["Mengganti nama ", " ke ", ""],
        arguments: &[0, 1],
    },
    // es; 2.20.0..=2.56.0
    Template {
        literals: &["Renombrando ", " a ", ""],
        arguments: &[0, 1],
    },
    // pt_BR; 2.56.0
    Template {
        literals: &["Renomeando ", " para ", ""],
        arguments: &[0, 1],
    },
    // fr; 2.20.0..=2.56.0
    Template {
        literals: &["Renommage de ", " en ", ""],
        arguments: &[0, 1],
    },
    // it; 2.20.0..=2.56.0
    Template {
        literals: &["Rinominazione di ", " in ", " in corso"],
        arguments: &[0, 1],
    },
    // ca; 2.20.0..=2.55.0
    Template {
        literals: &["S'està canviant el nom de ", " a ", ""],
        arguments: &[0, 1],
    },
    // pl; 2.30.0..=2.56.0
    Template {
        literals: &["Zmiana nazwy z ", " na ", ""],
        arguments: &[0, 1],
    },
    // vi; 2.20.0..=2.56.0
    Template {
        literals: &["Đổi tên ", " thành ", ""],
        arguments: &[0, 1],
    },
    // ru; 2.20.0..=2.56.0
    Template {
        literals: &["Переименование ", " в ", ""],
        arguments: &[0, 1],
    },
    // uk; 2.41.0..=2.56.0
    Template {
        literals: &["Перейменування ", " на ", ""],
        arguments: &[0, 1],
    },
    // bg; 2.20.0..=2.56.0
    Template {
        literals: &["Преименуване на „", "“ на „", "“"],
        arguments: &[0, 1],
    },
    // zh_CN; 2.20.0..=2.56.0
    Template {
        literals: &["重命名 ", " 至 ", ""],
        arguments: &[0, 1],
    },
    // zh_TW; 2.25.0..=2.56.0
    Template {
        literals: &["重新命名 ", " 至 ", ""],
        arguments: &[0, 1],
    },
    // ko; 2.20.0..=2.56.0
    Template {
        literals: &["이름 바꾸기, '", "'에서 '", "'(으)로"],
        arguments: &[0, 1],
    },
];
